# Generated by Django 4.0.3 on 2022-04-29 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0006_rename_usuario_mensajes_emisor_chats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensajes',
            name='destinatario',
        ),
        migrations.DeleteModel(
            name='Chats',
        ),
    ]
