# Generated by Django 4.0.3 on 2022-04-29 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0007_remove_mensajes_destinatario_delete_chats'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajes',
            name='destinatario',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
