# Generated by Django 4.0.3 on 2022-04-21 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posteos_nuevos',
            name='img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
