# Generated by Django 4.0.3 on 2022-04-25 02:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posteos_nuevos',
            name='autor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='posteos_nuevos',
            name='img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
