# Generated by Django 4.0.3 on 2022-03-30 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appblog', '0002_comentarios_nuevos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarios_nuevos',
            name='post',
            field=models.CharField(max_length=30),
        ),
    ]
