# Generated by Django 4.0.3 on 2022-03-31 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appblog', '0003_alter_comentarios_nuevos_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post_random',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Comentarios_nuevos',
        ),
    ]
