# Generated by Django 4.0.3 on 2022-04-07 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appblog', '0004_post_random_delete_comentarios_nuevos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posteos_nuevos',
            name='post',
            field=models.TextField(max_length=1200),
        ),
        migrations.AlterField(
            model_name='posteos_nuevos',
            name='titulo',
            field=models.CharField(max_length=60),
        ),
    ]
