# Generated by Django 4.0.3 on 2022-04-19 19:42

import ckeditor_uploader.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appblog', '0008_alter_posteos_nuevos_post_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='posteos_nuevos',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='posteos_nuevos',
            name='post',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Post'),
        ),
    ]
