# Generated by Django 4.0.3 on 2022-04-19 19:53

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appblog', '0009_posteos_nuevos_fecha_alter_posteos_nuevos_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posteos_nuevos',
            name='post',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Post'),
        ),
    ]
