# Generated by Django 4.0.3 on 2022-04-19 23:12

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appblog', '0010_alter_posteos_nuevos_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posteos_nuevos',
            name='fecha',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='posteos_nuevos',
            name='post',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
